import type { TypeDefinition } from "@/types/types";

export const TYPE_DEFINITIONS: TypeDefinition[] = [
  {
    name: "FORGE",
    title: "The System Crafter",
    concept: "Turns plans into working systems.",
    genomeProfile: {
      execution: 5,
      architecture: 4,
      innovation: 3,
      community: 1,
      leadership: 3,
      optimization: 4,
      research: 2,
      reliability: 4,
      craft: 2,
      openness: 2,
    },
  },
  {
    name: "ORBIT",
    title: "The Network Steward",
    concept: "Keeps people, issues, reviews, and projects moving around a shared center.",
    genomeProfile: {
      execution: 3,
      architecture: 2,
      innovation: 2,
      community: 5,
      leadership: 4,
      optimization: 2,
      research: 2,
      reliability: 3,
      craft: 3,
      openness: 5,
    },
  },
  {
    name: "NOVA",
    title: "The Frontier Spark",
    concept: "Opens new technical directions through experiments and prototypes.",
    genomeProfile: {
      execution: 3,
      architecture: 2,
      innovation: 5,
      community: 2,
      leadership: 2,
      optimization: 2,
      research: 4,
      reliability: 1,
      craft: 3,
      openness: 4,
    },
  },
  {
    name: "PULSE",
    title: "The Momentum Keeper",
    concept: "Maintains visible rhythm across commits, issues, and project updates.",
    genomeProfile: {
      execution: 5,
      architecture: 2,
      innovation: 2,
      community: 4,
      leadership: 3,
      optimization: 2,
      research: 1,
      reliability: 5,
      craft: 2,
      openness: 3,
    },
  },
  {
    name: "ECHO",
    title: "The Knowledge Resonator",
    concept: "Turns technical work into reusable knowledge for others.",
    genomeProfile: {
      execution: 2,
      architecture: 2,
      innovation: 3,
      community: 4,
      leadership: 3,
      optimization: 1,
      research: 5,
      reliability: 3,
      craft: 5,
      openness: 4,
    },
  },
  {
    name: "VECTOR",
    title: "The Direction Shaper",
    concept: "Sets technical direction and converts it into execution paths.",
    genomeProfile: {
      execution: 5,
      architecture: 4,
      innovation: 2,
      community: 3,
      leadership: 5,
      optimization: 3,
      research: 2,
      reliability: 4,
      craft: 3,
      openness: 3,
    },
  },
  {
    name: "CORE",
    title: "The Stability Anchor",
    concept: "Protects project reliability through maintenance and structure.",
    genomeProfile: {
      execution: 3,
      architecture: 4,
      innovation: 1,
      community: 2,
      leadership: 3,
      optimization: 4,
      research: 2,
      reliability: 5,
      craft: 2,
      openness: 3,
    },
  },
  {
    name: "CIPHER",
    title: "The Silent Resolver",
    concept: "Solves difficult technical problems with limited public noise.",
    genomeProfile: {
      execution: 4,
      architecture: 3,
      innovation: 2,
      community: 1,
      leadership: 1,
      optimization: 5,
      research: 4,
      reliability: 3,
      craft: 1,
      openness: 1,
    },
  },
  {
    name: "PRISM",
    title: "The Experience Refiner",
    concept: "Makes projects readable, usable, and visually clear.",
    genomeProfile: {
      execution: 3,
      architecture: 2,
      innovation: 4,
      community: 3,
      leadership: 3,
      optimization: 1,
      research: 2,
      reliability: 2,
      craft: 5,
      openness: 4,
    },
  },
  {
    name: "QUANT",
    title: "The Logic Distiller",
    concept: "Reduces complex technical material into precise models and algorithms.",
    genomeProfile: {
      execution: 2,
      architecture: 3,
      innovation: 3,
      community: 1,
      leadership: 2,
      optimization: 5,
      research: 5,
      reliability: 3,
      craft: 2,
      openness: 2,
    },
  },
  {
    name: "APEX",
    title: "The Release Standard",
    concept: "Sets visible quality bars for public projects.",
    genomeProfile: {
      execution: 4,
      architecture: 4,
      innovation: 2,
      community: 3,
      leadership: 5,
      optimization: 3,
      research: 2,
      reliability: 5,
      craft: 4,
      openness: 4,
    },
  },
  {
    name: "FLUX",
    title: "The Adaptive Catalyst",
    concept: "Moves quickly across changing tools, domains, and implementation paths.",
    genomeProfile: {
      execution: 4,
      architecture: 2,
      innovation: 5,
      community: 3,
      leadership: 2,
      optimization: 2,
      research: 3,
      reliability: 1,
      craft: 3,
      openness: 4,
    },
  },
  {
    name: "VOID",
    title: "The Deep Signal",
    concept: "Shows narrow but intense technical depth with minimal public surface.",
    genomeProfile: {
      execution: 2,
      architecture: 2,
      innovation: 3,
      community: 1,
      leadership: 1,
      optimization: 4,
      research: 5,
      reliability: 2,
      craft: 1,
      openness: 1,
    },
  },
  {
    name: "ATLAS",
    title: "The System Cartographer",
    concept: "Maps complex systems so others can navigate and extend them.",
    genomeProfile: {
      execution: 3,
      architecture: 5,
      innovation: 2,
      community: 2,
      leadership: 4,
      optimization: 3,
      research: 4,
      reliability: 4,
      craft: 3,
      openness: 3,
    },
  },
  {
    name: "NEXUS",
    title: "The Integration Link",
    concept: "Connects repositories, people, APIs, and ecosystems.",
    genomeProfile: {
      execution: 4,
      architecture: 4,
      innovation: 3,
      community: 5,
      leadership: 3,
      optimization: 2,
      research: 2,
      reliability: 3,
      craft: 3,
      openness: 5,
    },
  },
  {
    name: "ZENITH",
    title: "The Public Standard",
    concept: "Combines trust, presentation, leadership, and openness into a visible reference point.",
    genomeProfile: {
      execution: 3,
      architecture: 4,
      innovation: 2,
      community: 4,
      leadership: 5,
      optimization: 3,
      research: 3,
      reliability: 5,
      craft: 5,
      openness: 5,
    },
  },
];

